[workspace]
resolver = "2"
members = [
    "cpr_bf",
    "cpr_bfvm"
]

[workspace.package]
version = "0.1.1"
authors = ["Wouter de Bruijn <wouter@wutru.io>"]
homepage = "https://github.com/cloone8/bfrs"
edition = "2021"

[workspace.dependencies]
cpr_bf = { path = "cpr_bf", version = "0.1.1" }
