[package]
name = "cpr_bf"
description = "A brainfuck interpreter"
version.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
log = "0.4.21"
num = "0.4.1"
